// Real portfolio snapshot — generated by `python scripts/export.py`.
// Re-run that script (or `npm run snapshot`) whenever you want fresh
// numbers; the npm script also commits + pushes which triggers Vercel
// to rebuild.

import snapshot from "./portfolio.json";

export type StrategyStatus = "deployed" | "killed" | "in-research";

export interface EquityPoint {
  date: string;
  returnPct: number;
}

export interface StrategyRow {
  magic: number;
  name: string;
  engine: string;
  symbol: string;
  firstSeenAt: string;
  trades: number;
  wins: number;
  winRatePct: number;
  netPnlPct: number;
  fromStrategyLab: boolean;
}

export interface OpenPosition {
  ticket: number;
  symbol: string;
  magic: number;
  volume: number;
  openTime: string;
  priceOpen: number;
  profit: number;
}

export interface BenchmarkSnapshot {
  returnPct: number;
  windowStart: string;
  windowEnd: string;
  startClose: number;
  endClose: number;
}

export interface PortfolioSnapshot {
  startDate: string;
  totalReturnPct: number;
  totalTrades: number;
  winRatePct: number;
  profitFactor: number;
  maxDrawdownPct: number;
  benchmark: BenchmarkSnapshot | null;
  strategiesResearched: number;
  strategiesDeployed: number;
  strategiesKilled: number;
  equityCurve: EquityPoint[];
  strategies: StrategyRow[];
  openPositions: OpenPosition[];
}

export const portfolio: PortfolioSnapshot = snapshot as PortfolioSnapshot;
